apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  serviceName: {{ .Values.appName }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: '{{ .Values.image.name }}:{{ .Values.image.tag }}'
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: {{ .Values.env.JAVA_OPTS }}
            - name: GEOSTORE_OVR_OPT
              value: "-Dgeostore-ovr=file:///config/geostore-datasource-ovr.properties"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: datadir
              mountPath: /var/mapstore/datadir
            - name: ovr-properties
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: mapstore-pvc
        - name: ovr-properties
          secret:
            secretName: ovr-secret
